const DATABASE_NAME = '@gameplay';



const COLLECTION_USER =`${DATABASE_NAME}:user`;
const COLLECTION_APPOINTMENTS =`${DATABASE_NAME}:APPOINTMENTS`;

export {
  COLLECTION_APPOINTMENTS,
  COLLECTION_USER
}